from __future__ import annotations

"""Build a song-level pre-release score table for the 50 GoldenAI tracks.

Inputs (auto-detected under PROJECT_ROOT/data):
- songs.csv or data/songs/songs.csv
- a market score CSV such as:
  - subgenre_opportunity_score.csv
  - genre_signal_opportunity_score.csv
  - market_gap_opportunity_score.csv
  - data/market/market_opportunity_scores.csv

Outputs:
- data/song_scores.csv
- data/song_score_unmatched.csv
- reports/song_score_summary.md

This script does not invent lyric/audio scores. It creates a provisional
pre-release score from market opportunity + metadata completeness only.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable
import re

import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# Project paths
# -----------------------------------------------------------------------------

def find_project_root(start: Path) -> Path:
    """Walk upward until a folder containing data/ is found."""
    for candidate in [start, *start.parents]:
        if (candidate / "data").exists():
            return candidate
    # Expected location: PROJECT/src/src_final/src_final/04_prepare_song_scores.py
    return start.parents[3]


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = find_project_root(SCRIPT_DIR)
DATA_DIR = PROJECT_ROOT / "data"
REPORTS_DIR = PROJECT_ROOT / "reports"

OUTPUT_FILE = DATA_DIR / "song_scores.csv"
UNMATCHED_FILE = DATA_DIR / "song_score_unmatched.csv"
SUMMARY_FILE = REPORTS_DIR / "song_score_summary.md"


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

# This is a provisional pre-release score because DistroKid/Spotify performance
# data is not available yet.
MARKET_WEIGHT = 0.85
METADATA_WEIGHT = 0.15

HIGH_THRESHOLD = 80.0
MID_THRESHOLD = 65.0

SONG_FILE_CANDIDATES = [
    DATA_DIR / "songs.csv",
    DATA_DIR / "songs" / "songs.csv",
    DATA_DIR / "suno_generation_plan.csv",
]

MARKET_FILE_CANDIDATES = [
    DATA_DIR / "subgenre_opportunity_score.csv",
    DATA_DIR / "subgenre_opportunity_scores.csv",
    DATA_DIR / "genre_signal_opportunity_score.csv",
    DATA_DIR / "market_gap_opportunity_score.csv",
    DATA_DIR / "genre_signal_score.csv",
    DATA_DIR / "market" / "market_opportunity_scores.csv",
]


# -----------------------------------------------------------------------------
# Column aliases
# -----------------------------------------------------------------------------

SONG_ALIASES = {
    "track_id": ["track_id", "song_id", "id", "internal_code"],
    "title": ["public_title", "title", "song_title", "track_title"],
    "content_type": ["content_type", "type", "song_type"],
    "language": ["primary_language", "language", "lang"],
    "genre": ["genre_family", "genre", "main_genre"],
    "subgenre": ["subgenre", "sub_genre", "genre_subtype"],
    "country": ["target_country", "country", "market", "country_code"],
    "lyric_theme": ["lyric_theme", "theme", "lyrics_theme"],
    "mood": ["mood", "emotion"],
    "audio_path": ["audio_path", "file_path", "audio_file"],
    "lyrics_path": ["lyrics_path", "lyric_path", "lyrics_file"],
    "existing_market_score": [
        "market_opportunity_score",
        "opportunity_score",
        "market_score",
    ],
}

MARKET_ALIASES = {
    "country": ["target_country", "country", "market", "country_code"],
    "language": ["primary_language", "language", "lang"],
    "genre": ["genre_family", "genre", "main_genre"],
    "subgenre": ["subgenre", "sub_genre", "genre_subtype"],
    "score": [
        "subgenre_opportunity_score",
        "market_opportunity_score",
        "opportunity_score",
        "genre_signal_score",
        "market_gap_score",
        "final_score",
        "score",
    ],
}


@dataclass(frozen=True)
class MatchResult:
    score: float | None
    level: str
    source_rows: int


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

def first_existing_file(candidates: Iterable[Path], kind: str) -> Path:
    for path in candidates:
        if path.exists():
            return path

    # Flexible fallback for names generated by older scripts.
    if kind == "market":
        patterns = [
            "*subgenre*opportunity*.csv",
            "*genre*signal*.csv",
            "*market*gap*.csv",
            "*opportunity*score*.csv",
        ]
        matches: list[Path] = []
        for pattern in patterns:
            matches.extend(DATA_DIR.rglob(pattern))
        matches = [p for p in matches if p.name != OUTPUT_FILE.name]
        if matches:
            return sorted(matches, key=lambda p: p.stat().st_mtime, reverse=True)[0]

    attempted = "\n".join(f"- {p}" for p in candidates)
    raise FileNotFoundError(
        f"Could not find the {kind} CSV. Checked:\n{attempted}"
    )


def pick_column(df: pd.DataFrame, aliases: list[str]) -> str | None:
    lower_to_original = {str(col).strip().lower(): col for col in df.columns}
    for alias in aliases:
        if alias.lower() in lower_to_original:
            return lower_to_original[alias.lower()]
    return None


def canonicalize(df: pd.DataFrame, aliases: dict[str, list[str]]) -> pd.DataFrame:
    """Create canonical columns while preserving all original columns."""
    result = df.copy()
    for canonical, candidates in aliases.items():
        source = pick_column(result, candidates)
        if source is not None:
            result[canonical] = result[source]
        elif canonical not in result.columns:
            result[canonical] = pd.NA
    return result


def clean_text(value: object) -> str:
    if pd.isna(value):
        return ""
    text = str(value).strip()
    if text.upper() in {"VERIFY_REQUIRED", "NAN", "NONE", "NULL", "N/A"}:
        return ""
    return re.sub(r"\s+", " ", text)


def key(value: object) -> str:
    """Normalize text for tolerant matching."""
    text = clean_text(value).lower()
    text = text.replace("&", "and")
    text = re.sub(r"[^a-z0-9]+", "", text)
    return text


def numeric_score(series: pd.Series) -> pd.Series:
    """Convert a score column to a 0-100 scale."""
    values = pd.to_numeric(series, errors="coerce")
    valid = values.dropna()
    if valid.empty:
        return values

    max_value = float(valid.max())
    if max_value <= 1.5:      # e.g. 0.82
        values = values * 100
    elif max_value <= 10.0:   # e.g. 8.2
        values = values * 10

    return values.clip(lower=0, upper=100)


def metadata_score(row: pd.Series) -> tuple[float, list[str]]:
    """Calculate completeness without pretending to evaluate musical quality."""
    required = {
        "track_id": 20,
        "title": 20,
        "subgenre": 20,
        "country": 15,
        "content_type": 10,
        "genre": 5,
        "mood": 5,
        "audio_path": 5,
    }

    # Vocal songs need language/theme; instrumental songs do not.
    content_type = key(row.get("content_type"))
    is_vocal = content_type in {"vocal", "withlyrics", "lyrics", "song"}
    if is_vocal:
        required["language"] = 10
        required["lyric_theme"] = 5

    earned = 0.0
    total = float(sum(required.values()))
    missing: list[str] = []

    for field, points in required.items():
        if clean_text(row.get(field)):
            earned += points
        else:
            missing.append(field)

    return round(100 * earned / total, 2), missing


def build_market_keys(market: pd.DataFrame) -> pd.DataFrame:
    result = market.copy()
    for col in ["country", "language", "genre", "subgenre"]:
        result[f"_{col}_key"] = result[col].map(key)
    result["_score"] = numeric_score(result["score"])
    return result[result["_score"].notna()].copy()


def mean_match(df: pd.DataFrame, mask: pd.Series, level: str) -> MatchResult | None:
    matched = df.loc[mask, "_score"].dropna()
    if matched.empty:
        return None
    return MatchResult(
        score=round(float(matched.mean()), 2),
        level=level,
        source_rows=int(len(matched)),
    )


def match_market_score(row: pd.Series, market: pd.DataFrame) -> MatchResult:
    """Use the most specific available market match, then fall back safely."""
    country = key(row.get("country"))
    language = key(row.get("language"))
    genre = key(row.get("genre"))
    subgenre = key(row.get("subgenre"))

    # A manually supplied score in songs.csv takes priority.
    existing = pd.to_numeric(
        pd.Series([row.get("existing_market_score")]), errors="coerce"
    ).iloc[0]
    if pd.notna(existing):
        if existing <= 1.5:
            existing *= 100
        elif existing <= 10:
            existing *= 10
        return MatchResult(round(float(np.clip(existing, 0, 100)), 2), "songs_csv", 1)

    attempts: list[tuple[pd.Series, str]] = []

    if subgenre and country and language:
        attempts.append((
            (market["_subgenre_key"] == subgenre)
            & (market["_country_key"] == country)
            & (market["_language_key"] == language),
            "subgenre+country+language",
        ))
    if subgenre and country:
        attempts.append((
            (market["_subgenre_key"] == subgenre)
            & (market["_country_key"] == country),
            "subgenre+country",
        ))
    if subgenre and language:
        attempts.append((
            (market["_subgenre_key"] == subgenre)
            & (market["_language_key"] == language),
            "subgenre+language",
        ))
    if subgenre:
        attempts.append((market["_subgenre_key"] == subgenre, "subgenre"))
    if genre and country:
        attempts.append((
            (market["_genre_key"] == genre)
            & (market["_country_key"] == country),
            "genre+country",
        ))
    if genre:
        attempts.append((market["_genre_key"] == genre, "genre"))

    for mask, level in attempts:
        result = mean_match(market, mask, level)
        if result is not None:
            return result

    return MatchResult(None, "unmatched", 0)


def match_confidence(level: str) -> float:
    return {
        "songs_csv": 1.00,
        "subgenre+country+language": 1.00,
        "subgenre+country": 0.90,
        "subgenre+language": 0.85,
        "subgenre": 0.75,
        "genre+country": 0.60,
        "genre": 0.45,
        "unmatched": 0.00,
    }.get(level, 0.00)


def tier_for(score: float | None, confidence: float) -> str:
    if score is None or pd.isna(score) or confidence < 0.40:
        return "Needs Data"
    if score >= HIGH_THRESHOLD:
        return "High"
    if score >= MID_THRESHOLD:
        return "Mid"
    return "Low"


def recommendation_for(tier: str) -> str:
    return {
        "High": "Priority release test",
        "Mid": "Secondary release test",
        "Low": "Hold or revise before release",
        "Needs Data": "Complete missing data before deciding",
    }[tier]


def write_summary(result: pd.DataFrame, songs_file: Path, market_file: Path) -> None:
    tier_counts = result["tier"].value_counts(dropna=False).to_dict()
    unmatched = int(result["market_score"].isna().sum())

    top = result[result["pre_release_score"].notna()].nlargest(
        10, "pre_release_score"
    )

    lines = [
        "# GoldenAI Song Score Summary",
        "",
        f"- Songs source: `{songs_file.relative_to(PROJECT_ROOT)}`",
        f"- Market source: `{market_file.relative_to(PROJECT_ROOT)}`",
        f"- Total tracks: **{len(result)}**",
        f"- Unmatched market scores: **{unmatched}**",
        f"- Score formula: **{MARKET_WEIGHT:.0%} market + {METADATA_WEIGHT:.0%} metadata**",
        "- Important: this is a provisional pre-release score, not a prediction of streams or revenue.",
        "",
        "## Tier counts",
        "",
    ]

    for tier in ["High", "Mid", "Low", "Needs Data"]:
        lines.append(f"- {tier}: {tier_counts.get(tier, 0)}")

    lines.extend(["", "## Current top tracks", ""])
    if top.empty:
        lines.append("No track has enough data to produce a score yet.")
    else:
        lines.append("| Rank | Track ID | Title | Market | Pre-release | Confidence | Tier |")
        lines.append("|---:|---|---|---:|---:|---:|---|")
        for rank, (_, row) in enumerate(top.iterrows(), start=1):
            lines.append(
                f"| {rank} | {row['track_id']} | {row['title']} | "
                f"{row['market_score']:.1f} | {row['pre_release_score']:.1f} | "
                f"{row['confidence']:.0%} | {row['tier']} |"
            )

    SUMMARY_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    songs_file = first_existing_file(SONG_FILE_CANDIDATES, "songs")
    market_file = first_existing_file(MARKET_FILE_CANDIDATES, "market")

    print(f"Project root: {PROJECT_ROOT}")
    print(f"Songs file:  {songs_file}")
    print(f"Market file: {market_file}")

    songs_raw = pd.read_csv(songs_file)
    market_raw = pd.read_csv(market_file)

    songs = canonicalize(songs_raw, SONG_ALIASES)
    market = canonicalize(market_raw, MARKET_ALIASES)

    if songs["track_id"].map(clean_text).eq("").any():
        raise ValueError("songs.csv contains blank track_id values.")
    if songs["track_id"].astype(str).duplicated().any():
        duplicates = songs.loc[
            songs["track_id"].astype(str).duplicated(keep=False), "track_id"
        ].tolist()
        raise ValueError(f"Duplicate track_id values found: {duplicates}")

    if market["score"].isna().all():
        raise ValueError(
            "The market CSV has no recognized score column. Expected one of: "
            + ", ".join(MARKET_ALIASES["score"])
        )

    market = build_market_keys(market)
    rows: list[dict[str, object]] = []

    for _, song in songs.iterrows():
        meta_score, missing_fields = metadata_score(song)
        match = match_market_score(song, market)
        market_conf = match_confidence(match.level)

        # Evidence confidence combines market match quality and metadata completeness.
        confidence = round(
            0.70 * market_conf + 0.30 * (meta_score / 100), 3
        )

        if match.score is None:
            pre_release_score: float | None = None
        else:
            pre_release_score = round(
                MARKET_WEIGHT * match.score + METADATA_WEIGHT * meta_score,
                2,
            )

        tier = tier_for(pre_release_score, confidence)

        rows.append({
            "track_id": clean_text(song.get("track_id")),
            "title": clean_text(song.get("title")),
            "content_type": clean_text(song.get("content_type")),
            "language": clean_text(song.get("language")),
            "genre": clean_text(song.get("genre")),
            "subgenre": clean_text(song.get("subgenre")),
            "target_country": clean_text(song.get("country")),
            "lyric_theme": clean_text(song.get("lyric_theme")),
            "mood": clean_text(song.get("mood")),
            "market_score": match.score,
            "market_match_level": match.level,
            "market_source_rows": match.source_rows,
            "metadata_score": meta_score,
            "lyric_score": pd.NA,
            "audio_score": pd.NA,
            "pre_release_score": pre_release_score,
            "confidence": confidence,
            "tier": tier,
            "recommendation": recommendation_for(tier),
            "missing_fields": ";".join(missing_fields),
            "score_version": "pre_release_v1_market_metadata",
        })

    result = pd.DataFrame(rows)
    result["rank"] = result["pre_release_score"].rank(
        method="min", ascending=False, na_option="bottom"
    ).astype("Int64")

    ordered_columns = [
        "rank",
        "track_id",
        "title",
        "content_type",
        "language",
        "genre",
        "subgenre",
        "target_country",
        "lyric_theme",
        "mood",
        "market_score",
        "market_match_level",
        "market_source_rows",
        "metadata_score",
        "lyric_score",
        "audio_score",
        "pre_release_score",
        "confidence",
        "tier",
        "recommendation",
        "missing_fields",
        "score_version",
    ]
    result = result[ordered_columns].sort_values(
        ["rank", "track_id"], na_position="last"
    )

    result.to_csv(OUTPUT_FILE, index=False)
    result[result["market_score"].isna()].to_csv(UNMATCHED_FILE, index=False)
    write_summary(result, songs_file, market_file)

    print("\nSong score preparation completed.")
    print(f"- Tracks processed: {len(result)}")
    print(f"- Scored tracks: {result['pre_release_score'].notna().sum()}")
    print(f"- Unmatched tracks: {result['market_score'].isna().sum()}")
    print(f"- Output: {OUTPUT_FILE}")
    print(f"- Unmatched: {UNMATCHED_FILE}")
    print(f"- Summary: {SUMMARY_FILE}")


if __name__ == "__main__":
    main()